import 'package:hive/hive.dart';

part 'thought_log.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0)
class ThoughtLog extends HiveObject {
  @HiveField(0)
  String trigger;

  @HiveField(1)
  String automaticThought;

  @HiveField(2)
  String distortionType;

  @HiveField(3)
  String emotion;

  @HiveField(4)
  int intensity; // 1–10

  @HiveField(5)
  String? reframe; // Optional field

  @HiveField(6)
  DateTime dateLogged;

  ThoughtLog({
    required this.trigger,
    required this.automaticThought,
    required this.distortionType,
    required this.emotion,
    required this.intensity,
    this.reframe,
    required this.dateLogged,
  });

  // Helper method for displaying in list/detail
  String get formattedDate {
    return '${dateLogged.day}/${dateLogged.month}/${dateLogged.year}';
  }
}

// Predefined lists for dropdowns
const List<String> distortionTypes = [
  'Catastrophizing',
  'Black-and-white thinking',
  'Mind reading',
  'Overgeneralization',
  'Emotional reasoning',
  'Magnification (or Minimization)',
  'Personalization',
  'Should Statements',
  'Labeling',
  'Filtering',
  'Discounting the Positive',
  'Jumping to Conclusions',
];

const List<String> emotionTypes = [
  'Sadness',
  'Anger',
  'Anxiety',
  'Frustration',
  'Guilt',
  'Shame',
  'Hopelessness',
  'Helplessness',
  'Disappointment',
  'Irritation',
  'Fear',
  'Joy', // Even negative thoughts can sometimes have a nuanced emotion
];